version: '3.2'
services:

    orion:
        image: fiware/orion
        hostname: orion
        container_name: fiware-orion
        ports:
            - "1026:1026"
        command: -dbhost mongodb -logLevel DEBUG -noCache
        networks:
            - posadas-net

    mongodb:
        image: mongo:3.6
        container_name: mongodb
        hostname: mongodb
        ports:
            - "27017:27017"
        command: --bind_ip_all --smallfiles
        volumes:
            - mongo_db_volume:/data
        networks:
            - posadas-net

    adminmongo:
        image: mrvautin/adminmongo
        ports:
            - 1234:1234
        environment:
            - HOST=0.0.0.0
        networks:
            - posadas-net

networks:
    posadas-net:
        name: posadas-network

volumes:
    posadas_db_volume:
    mongo_db_volume:
