miObjeto = {
  data: [
    {
      location_id: "805321",
      name: "Hotel Grand Crucero Posadas Express",
      latitude: "-27.370586",
      longitude: "-55.89636",
      num_reviews: "144",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0d/ad/1d/48/20161119-191109-largejpg.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0d/ad/1d/48/20161119-191109-largejpg.jpg",
            height: "50",
          },
          original: {
            width: "4128",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0d/ad/1d/48/20161119-191109-largejpg.jpg",
            height: "3096",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/ad/1d/48/20161119-191109-largejpg.jpg",
            height: "412",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0d/ad/1d/48/20161119-191109-largejpg.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2016-11-20T04:47:11-0500",
        caption: "",
        id: "229449032",
        helpful_votes: "1",
        published_date: "2016-11-20T04:47:11-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2019",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2019_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2019",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.6051735877990723",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "1",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#1 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.36239466512903995",
      distance_string: null,
      bearing: "southwest",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$34 - $47",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "0c4d5668-6336-4967-bb41-83774e1a2b09",
    },
    {
      location_id: "2170683",
      name: "Hotel Urbano Posadas",
      latitude: "-27.366388",
      longitude: "-55.89749",
      num_reviews: "553",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0a/02/f3/8e/hotel-urbano.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0a/02/f3/8e/hotel-urbano.jpg",
            height: "50",
          },
          original: {
            width: "3151",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0a/02/f3/8e/hotel-urbano.jpg",
            height: "2682",
          },
          large: {
            width: "529",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0a/02/f3/8e/hotel-urbano.jpg",
            height: "450",
          },
          medium: {
            width: "241",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0a/02/f3/8e/hotel-urbano.jpg",
            height: "205",
          },
        },
        is_blessed: true,
        uploaded_date: "2016-01-11T15:34:07-0500",
        caption: "Hotel Urbano",
        id: "167965582",
        helpful_votes: "3",
        published_date: "2016-01-11T15:34:07-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2017",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2017_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2017",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2013",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2013_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2013",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2012",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2012_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2012",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.755030870437622",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "2",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#2 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.30766756402167883",
      distance_string: null,
      bearing: "west",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$88 - $105",
      hotel_class: "4.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "5b18f8de-ed14-4e2f-a213-7f39677b08f2",
    },
    {
      location_id: "1942914",
      name: "Maitei Hotel Resort & Spa",
      latitude: "-27.397102",
      longitude: "-55.962395",
      num_reviews: "478",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/05/5a/9d/b3/maitei-posadas-hotel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/05/5a/9d/b3/maitei-posadas-hotel.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/05/5a/9d/b3/maitei-posadas-hotel.jpg",
            height: "1500",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/05/5a/9d/b3/maitei-posadas-hotel.jpg",
            height: "412",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/05/5a/9d/b3/maitei-posadas-hotel.jpg",
            height: "187",
          },
        },
        is_blessed: true,
        uploaded_date: "2014-02-06T19:44:20-0500",
        caption: "Perfect temperature",
        id: "89824691",
        helpful_votes: "6",
        published_date: "2014-02-06T19:44:20-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2015",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2015_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2015",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2014",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2014_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2014",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2013",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2013_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2013",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2012",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2012_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2012",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.8319458961486816",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "3",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#3 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "4.783018121545358",
      distance_string: null,
      bearing: "southwest",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$67 - $75",
      hotel_class: "4.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "9d2ccfeb-925e-4f92-9326-96fb07e0b13d",
    },
    {
      location_id: "898911",
      name: "Posadas Hotel",
      latitude: "-27.366957",
      longitude: "-55.89517",
      num_reviews: "325",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/09/b4/2f/a9/posadas-hotel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/09/b4/2f/a9/posadas-hotel.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/09/b4/2f/a9/posadas-hotel.jpg",
            height: "1333",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/09/b4/2f/a9/posadas-hotel.jpg",
            height: "367",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/09/b4/2f/a9/posadas-hotel.jpg",
            height: "167",
          },
        },
        is_blessed: true,
        uploaded_date: "2015-12-08T08:48:21-0500",
        caption: "MATRIMONIAL STANDARD",
        id: "162803625",
        helpful_votes: "1",
        published_date: "2015-12-08T08:48:21-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.152324676513672",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "4",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#4 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.16604136502771624",
      distance_string: null,
      bearing: "west",
      rating: "3.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$47",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "473991fd-b157-4ee1-902b-a9ba210c5bfc",
    },
    {
      location_id: "1569765",
      name: "Continental Posadas Hotel",
      latitude: "-27.366964",
      longitude: "-55.894268",
      num_reviews: "313",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/17/b3/5c/34/continental-posadas-hotel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/17/b3/5c/34/continental-posadas-hotel.jpg",
            height: "50",
          },
          original: {
            width: "4032",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/17/b3/5c/34/continental-posadas-hotel.jpg",
            height: "3024",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/17/b3/5c/34/continental-posadas-hotel.jpg",
            height: "412",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/17/b3/5c/34/continental-posadas-hotel.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-05-28T09:16:03-0400",
        caption: "",
        id: "397630516",
        helpful_votes: "0",
        published_date: "2019-05-28T09:16:03-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.450909376144409",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "5",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#5 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.11161312801571983",
      distance_string: null,
      bearing: "west",
      rating: "3.5",
      is_closed: false,
      open_now_text: "Open Now",
      is_long_closed: false,
      price_level: "$",
      price: "$52 - $62",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "46cb6572-973f-4e1b-b7f7-0a1bc46e1aef",
    },
    {
      location_id: "12494626",
      name: "AVEMAR Apart Hotel",
      latitude: "-27.374441",
      longitude: "-55.887688",
      num_reviews: "10",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0f/7a/b5/08/avemar-apart-hotel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0f/7a/b5/08/avemar-apart-hotel.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0f/7a/b5/08/avemar-apart-hotel.jpg",
            height: "1325",
          },
          large: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-w/0f/7a/b5/08/avemar-apart-hotel.jpg",
            height: "678",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0f/7a/b5/08/avemar-apart-hotel.jpg",
            height: "364",
          },
        },
        is_blessed: true,
        uploaded_date: "2017-06-04T15:59:09-0400",
        caption: "",
        id: "259699976",
        helpful_votes: "6",
        published_date: "2017-06-04T15:59:09-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.1809325218200684",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "6",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#6 Best Value of 72 places to stay in Posadas",
      subcategory_type: "specialty_hotel",
      subcategory_type_label: "Specialty Hotel",
      distance: "0.6155615197715888",
      distance_string: null,
      bearing: "southeast",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$42 - $47",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "c38d1e74-49d4-4d6d-a49f-6e434c04a070",
    },
    {
      location_id: "312805",
      ad_position: "inline1",
      ad_size: "8X8",
      doubleclick_zone: "sa.argentina.litoral",
      ancestors: [
        {
          subcategory: [
            {
              key: "province",
              name: "Province",
            },
          ],
          name: "Province of Misiones",
          abbrv: null,
          location_id: "312803",
        },
        {
          subcategory: [
            {
              key: "region",
              name: "Region",
            },
          ],
          name: "Litoral",
          abbrv: null,
          location_id: "312790",
        },
        {
          subcategory: [
            {
              key: "country",
              name: "Country",
            },
          ],
          name: "Argentina",
          abbrv: null,
          location_id: "294266",
        },
      ],
      detail: "0",
      page_type: "hotels",
      mob_ptype: "app_hotels",
    },
    {
      location_id: "10671368",
      name: "Apart Belgrano",
      latitude: "-27.363428",
      longitude: "-55.890614",
      num_reviews: "11",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/15/20/b5/77/suite-matrimonial-premium.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/15/20/b5/77/suite-matrimonial-premium.jpg",
            height: "50",
          },
          original: {
            width: "774",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/15/20/b5/77/suite-matrimonial-premium.jpg",
            height: "774",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-p/15/20/b5/77/suite-matrimonial-premium.jpg",
            height: "550",
          },
          medium: {
            width: "450",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/15/20/b5/77/suite-matrimonial-premium.jpg",
            height: "450",
          },
        },
        is_blessed: true,
        uploaded_date: "2018-10-22T14:35:31-0400",
        caption: "Suite matrimonial Premium",
        id: "354465143",
        helpful_votes: "0",
        published_date: "2018-10-22T14:35:31-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.125398635864258",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "7",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#7 Best Value of 72 places to stay in Posadas",
      subcategory_type: "condo",
      subcategory_type_label: "Condominium",
      distance: "0.24972167926481195",
      distance_string: null,
      bearing: "northeast",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$70 - $80",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "5702e729-dcd8-4728-a609-fc2db7ce5290",
    },
    {
      location_id: "15002276",
      name: "Como en casa Hostel",
      latitude: "-27.369745",
      longitude: "-55.89815",
      num_reviews: "5",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/15/23/d6/44/como-en-casa-hostel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/15/23/d6/44/como-en-casa-hostel.jpg",
            height: "50",
          },
          original: {
            width: "5184",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/15/23/d6/44/como-en-casa-hostel.jpg",
            height: "3456",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/15/23/d6/44/como-en-casa-hostel.jpg",
            height: "367",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/15/23/d6/44/como-en-casa-hostel.jpg",
            height: "167",
          },
        },
        is_blessed: true,
        uploaded_date: "2018-10-23T22:00:19-0400",
        caption: "",
        id: "354670148",
        helpful_votes: "0",
        published_date: "2018-10-23T22:00:19-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.017712354660034",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "8",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#8 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hostel",
      subcategory_type_label: "Hostel",
      distance: "0.4090761779253125",
      distance_string: null,
      bearing: "southwest",
      rating: "3.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$25",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "417c87b8-ddfe-4394-80ab-dbcc13e3fe84",
    },
    {
      location_id: "472203",
      name: "Julio Cesar Hotel",
      latitude: "-27.369583",
      longitude: "-55.895668",
      num_reviews: "206",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/10/89/ea/38/julio-cesar-hotel.jpg",
            height: "141",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/10/89/ea/38/julio-cesar-hotel.jpg",
            height: "50",
          },
          original: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-w/10/89/ea/38/julio-cesar-hotel.jpg",
            height: "576",
          },
          large: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/10/89/ea/38/julio-cesar-hotel.jpg",
            height: "576",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/10/89/ea/38/julio-cesar-hotel.jpg",
            height: "309",
          },
        },
        is_blessed: true,
        uploaded_date: "2017-09-04T05:00:03-0400",
        caption: "",
        id: "277473848",
        helpful_votes: "4",
        published_date: "2017-09-04T05:00:03-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.052170991897583",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "9",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#9 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.28251008714744924",
      distance_string: null,
      bearing: "southwest",
      rating: "3.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$60 - $82",
      hotel_class: "4.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "0e7a633f-1a88-4c41-9bef-b96fdd3b5279",
    },
    {
      location_id: "2367491",
      name: "Edificio Nicolas y Marcelo Siry",
      latitude: "-27.354225",
      longitude: "-55.89407",
      num_reviews: "69",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/11/de/e3/12/edificio-nicolas-y-marcelo.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/11/de/e3/12/edificio-nicolas-y-marcelo.jpg",
            height: "50",
          },
          original: {
            width: "1080",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/11/de/e3/12/edificio-nicolas-y-marcelo.jpg",
            height: "608",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/11/de/e3/12/edificio-nicolas-y-marcelo.jpg",
            height: "309",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/11/de/e3/12/edificio-nicolas-y-marcelo.jpg",
            height: "141",
          },
        },
        is_blessed: true,
        uploaded_date: "2018-01-25T09:55:53-0500",
        caption: "",
        id: "299819794",
        helpful_votes: "0",
        published_date: "2018-01-25T09:55:53-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.4322292804718018",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "10",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#10 Best Value of 72 places to stay in Posadas",
      subcategory_type: "condo",
      subcategory_type_label: "Condominium",
      distance: "0.8635525421590902",
      distance_string: null,
      bearing: "north",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$$",
      price: "$100 - $111",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [
          {
            value:
              "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=2367491&from=api&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=233154102&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkZy1e4bZAydMwU8t7J26FzVNJG9nKgMbwH-EKlDW-z2uZfbsViOFYu4hiCjxxITxNg&bapid=1&cs=11b7f0d50d60d890b949cc70ecd9cd233",
            label: "Hotel website",
            type: "url",
          },
        ],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "301ef5e6-743c-4a28-ac4e-b499a4e3acd3",
    },
    {
      location_id: "6772500",
      name: "Hotel Colon",
      latitude: "-27.370308",
      longitude: "-55.89491",
      num_reviews: "26",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/06/2f/4e/88/hotel-colon.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/06/2f/4e/88/hotel-colon.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/06/2f/4e/88/hotel-colon.jpg",
            height: "1500",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/06/2f/4e/88/hotel-colon.jpg",
            height: "413",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/06/2f/4e/88/hotel-colon.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2014-07-14T10:54:10-0400",
        caption: "Habitacion Triple",
        id: "103763592",
        helpful_votes: "0",
        published_date: "2014-07-14T10:54:10-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "2.8499443531036377",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "11",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#11 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.29457238797272867",
      distance_string: null,
      bearing: "southwest",
      rating: "3.0",
      is_closed: false,
      open_now_text: "Open Now",
      is_long_closed: false,
      price_level: "$",
      price: "$42 - $46",
      hotel_class: "2.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "e6c8ca0d-64f1-4553-8147-3185bcc6aa4c",
    },
    {
      location_id: "14869860",
      name: "Posadas la Hermosa",
      latitude: "-27.3761",
      longitude: "-55.893806",
      num_reviews: "3",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/b6/fa/a8/propertybuilding.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/b6/fa/a8/propertybuilding.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/fa/a8/propertybuilding.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/fa/a8/propertybuilding.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/b6/fa/a8/propertybuilding.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-10-17T19:17:35-0400",
        caption: "Property building",
        id: "431422120",
        helpful_votes: "0",
        published_date: "2019-10-17T19:17:35-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.070340633392334",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "12",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#12 Best Value of 72 places to stay in Posadas",
      subcategory_type: "specialty_inn",
      subcategory_type_label: "Specialty Inn",
      distance: "0.660011629358499",
      distance_string: null,
      bearing: "south",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$56",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "6c5dc521-6918-45a3-921a-9871a3a4e9ae",
    },
    {
      location_id: "3403556",
      name: "Urunday Apart Hotel",
      latitude: "-27.40846",
      longitude: "-55.903084",
      num_reviews: "26",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0c/17/9a/42/habitacion-matrimonial.jpg",
            height: "141",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0c/17/9a/42/habitacion-matrimonial.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0c/17/9a/42/habitacion-matrimonial.jpg",
            height: "1125",
          },
          large: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-w/0c/17/9a/42/habitacion-matrimonial.jpg",
            height: "576",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0c/17/9a/42/habitacion-matrimonial.jpg",
            height: "309",
          },
        },
        is_blessed: true,
        uploaded_date: "2016-07-20T18:28:56-0400",
        caption: "Habitación matrimonial",
        id: "202873410",
        helpful_votes: "0",
        published_date: "2016-07-20T18:28:56-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.2656068801879883",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "13",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#13 Best Value of 72 places to stay in Posadas",
      subcategory_type: "condo",
      subcategory_type_label: "Condominium",
      distance: "2.965647299932992",
      distance_string: null,
      bearing: "south",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$45 - $55",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "eadcbd2d-716d-4bd6-9c99-56a7c5a167af",
    },
    {
      location_id: "1924657",
      name: "Hotel Canciller",
      latitude: "-27.365921",
      longitude: "-55.89762",
      num_reviews: "38",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0f/74/a4/4a/hotel-canciller.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0f/74/a4/4a/hotel-canciller.jpg",
            height: "50",
          },
          original: {
            width: "940",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0f/74/a4/4a/hotel-canciller.jpg",
            height: "529",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0f/74/a4/4a/hotel-canciller.jpg",
            height: "309",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0f/74/a4/4a/hotel-canciller.jpg",
            height: "141",
          },
        },
        is_blessed: true,
        uploaded_date: "2017-06-02T09:04:52-0400",
        caption: "",
        id: "259302474",
        helpful_votes: "0",
        published_date: "2017-06-02T09:04:52-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.049207925796509",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "14",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#14 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.3189772793997753",
      distance_string: null,
      bearing: "west",
      rating: "3.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$52 - $63",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "bc2c9149-98d8-4635-89b6-f5c05dd6d359",
    },
    {
      location_id: "312805",
      ad_position: "inline2",
      ad_size: "8X8",
      doubleclick_zone: "sa.argentina.litoral",
      ancestors: [
        {
          subcategory: [
            {
              key: "province",
              name: "Province",
            },
          ],
          name: "Province of Misiones",
          abbrv: null,
          location_id: "312803",
        },
        {
          subcategory: [
            {
              key: "region",
              name: "Region",
            },
          ],
          name: "Litoral",
          abbrv: null,
          location_id: "312790",
        },
        {
          subcategory: [
            {
              key: "country",
              name: "Country",
            },
          ],
          name: "Argentina",
          abbrv: null,
          location_id: "294266",
        },
      ],
      detail: "0",
      page_type: "hotels",
      mob_ptype: "app_hotels",
    },
    {
      location_id: "20854282",
      name: "Habitaciones Villa Blosset",
      latitude: "-27.365822",
      longitude: "-55.886414",
      num_reviews: "0",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/23/44/50/18/caption.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/23/44/50/18/caption.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/23/44/50/18/caption.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/23/44/50/18/caption.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/23/44/50/18/caption.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2022-04-30T01:10:47-0400",
        caption: "",
        id: "591679512",
        helpful_votes: "0",
        published_date: "2022-04-30T01:10:47-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      ranking_position: "15",
      ranking_denominator: "72",
      ranking: "#15 Best Value of 72 places to stay in Posadas",
      distance: "0.37746197945564924",
      distance_string: null,
      bearing: "east",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$24 - $28",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "d7932ad4-47d9-43b2-9693-d0501e5b73f4",
    },
    {
      location_id: "5508246",
      name: "Hotel Oaky",
      latitude: "-27.402073",
      longitude: "-55.922943",
      num_reviews: "28",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/21/f6/d8/58/habitacion-triple-premium.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/21/f6/d8/58/habitacion-triple-premium.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/21/f6/d8/58/habitacion-triple-premium.jpg",
            height: "1125",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/21/f6/d8/58/habitacion-triple-premium.jpg",
            height: "309",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/21/f6/d8/58/habitacion-triple-premium.jpg",
            height: "141",
          },
        },
        is_blessed: true,
        uploaded_date: "2022-01-27T09:39:10-0500",
        caption: "Habitación triple premium",
        id: "569825368",
        helpful_votes: "0",
        published_date: "2022-01-27T09:39:10-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.076817750930786",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "16",
      ranking_denominator: "72",
      ranking_category: "bb",
      ranking: "#16 Best Value of 72 places to stay in Posadas",
      subcategory_type: "small_hotel",
      subcategory_type_label: "Small Hotel",
      distance: "3.0835802966913746",
      distance_string: null,
      bearing: "southwest",
      rating: "3.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$48 - $54",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "896dd077-b57a-4fec-9d2e-6592e8a4b11f",
    },
    {
      location_id: "21125810",
      name: "Hotel Posta Norte",
      latitude: "-27.385845",
      longitude: "-55.90378",
      num_reviews: "2",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "550",
            url: null,
            height: "550",
          },
          thumbnail: {
            width: "550",
            url: null,
            height: "550",
          },
          original: {
            width: "550",
            url: null,
            height: "550",
          },
          large: {
            width: "550",
            url: null,
            height: "550",
          },
          medium: {
            width: "550",
            url: null,
            height: "550",
          },
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "2.7359073162078857",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "17",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#17 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "1.499164018954755",
      distance_string: null,
      bearing: "southwest",
      rating: "2.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$53 - $60",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "bec0512a-6e73-443b-8c25-8a1050c69956",
    },
    {
      location_id: "2044942",
      name: "La Mision Posadas Hotel & Spa",
      latitude: "-27.399782",
      longitude: "-55.940502",
      num_reviews: "175",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0e/0f/38/88/photo7jpg.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0e/0f/38/88/photo7jpg.jpg",
            height: "50",
          },
          original: {
            width: "2048",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/0f/38/88/photo7jpg.jpg",
            height: "1536",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0e/0f/38/88/photo7jpg.jpg",
            height: "413",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0e/0f/38/88/photo7jpg.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2017-01-04T15:06:27-0500",
        caption: "",
        id: "235878536",
        helpful_votes: "2",
        published_date: "2017-01-04T15:06:27-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2016",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2016_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2016",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2015",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2015_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2015",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2014",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2014_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2014",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.48246693611145",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "18",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#18 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "3.735532964825501",
      distance_string: null,
      bearing: "southwest",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$69",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "1ae7d800-e642-4641-a58a-1d7c48022a0f",
    },
    {
      location_id: "6638687",
      name: "Costa Azul Hotel",
      latitude: "-27.37151",
      longitude: "-55.90841",
      num_reviews: "18",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0d/dd/45/d7/acceso-al-hotel-y-cocheras.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0d/dd/45/d7/acceso-al-hotel-y-cocheras.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0d/dd/45/d7/acceso-al-hotel-y-cocheras.jpg",
            height: "1500",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/dd/45/d7/acceso-al-hotel-y-cocheras.jpg",
            height: "413",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0d/dd/45/d7/acceso-al-hotel-y-cocheras.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2016-12-13T06:09:15-0500",
        caption: "acceso al hotel y cocheras",
        id: "232605143",
        helpful_votes: "0",
        published_date: "2016-12-13T06:09:15-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "2.5443480014801025",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "19",
      ranking_denominator: "72",
      ranking_category: "bb",
      ranking: "#19 Best Value of 72 places to stay in Posadas",
      subcategory_type: "small_hotel",
      subcategory_type_label: "Small Hotel",
      distance: "1.0344492462399242",
      distance_string: null,
      bearing: "west",
      rating: "2.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$58 - $65",
      hotel_class: "4.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "ae02df9b-159c-4397-95a5-8d9a869fe598",
    },
    {
      location_id: "2315757",
      name: "Hosteria Maryland",
      latitude: "-27.382013",
      longitude: "-55.90335",
      num_reviews: "20",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/02/58/bd/f1/desayunador-y-pequeno.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/02/58/bd/f1/desayunador-y-pequeno.jpg",
            height: "50",
          },
          original: {
            width: "3000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/02/58/bd/f1/desayunador-y-pequeno.jpg",
            height: "4000",
          },
          large: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-w/02/58/bd/f1/desayunador-y-pequeno.jpg",
            height: "1365",
          },
          medium: {
            width: "337",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/02/58/bd/f1/desayunador-y-pequeno.jpg",
            height: "450",
          },
        },
        is_blessed: true,
        uploaded_date: "2012-02-21T15:44:42-0500",
        caption: "Desayunador y pequeño living en la entrada",
        id: "39370225",
        helpful_votes: "12",
        published_date: "2012-02-22T07:39:08-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.0627007484436035",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "20",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#20 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "1.255859904309503",
      distance_string: null,
      bearing: "southwest",
      rating: "3.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$39",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "4d19d8f2-4a81-4fca-878e-5bcadeef9b98",
    },
    {
      location_id: "20857823",
      name: "Hotel Vanderloo",
      latitude: "-27.37531",
      longitude: "-55.897762",
      num_reviews: "0",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/1b/9c/ec/5d/5931564.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1b/9c/ec/5d/5931564.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/9c/ec/5d/5931564.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/9c/ec/5d/5931564.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1b/9c/ec/5d/5931564.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2020-07-24T00:16:15-0400",
        caption: "Hotel Vanderloo",
        id: "463268957",
        helpful_votes: "0",
        published_date: "2020-07-24T00:16:15-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      ranking_position: "21",
      ranking_denominator: "72",
      ranking: "#21 Best Value of 72 places to stay in Posadas",
      distance: "0.6821849302403911",
      distance_string: null,
      bearing: "southwest",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$38",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "20c066e1-fe6e-4a1b-9191-1cb788582842",
    },
    {
      location_id: "14868044",
      name: "Lavalle Hostel",
      latitude: "-27.370537",
      longitude: "-55.905777",
      num_reviews: "0",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/b6/e7/42/facadeentrance.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/b6/e7/42/facadeentrance.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/e7/42/facadeentrance.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/e7/42/facadeentrance.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/b6/e7/42/facadeentrance.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-10-17T19:14:23-0400",
        caption: "Facade/entrance",
        id: "431417154",
        helpful_votes: "0",
        published_date: "2019-10-17T19:14:23-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      ranking_position: "22",
      ranking_denominator: "72",
      ranking: "#22 Best Value of 72 places to stay in Posadas",
      distance: "0.8597300898859882",
      distance_string: null,
      bearing: "west",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$24 - $25",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "bbfce91b-c870-4e26-911a-bcf3d9dbde7c",
    },
    {
      location_id: "312805",
      ad_position: "inline3",
      ad_size: "8X8",
      doubleclick_zone: "sa.argentina.litoral",
      ancestors: [
        {
          subcategory: [
            {
              key: "province",
              name: "Province",
            },
          ],
          name: "Province of Misiones",
          abbrv: null,
          location_id: "312803",
        },
        {
          subcategory: [
            {
              key: "region",
              name: "Region",
            },
          ],
          name: "Litoral",
          abbrv: null,
          location_id: "312790",
        },
        {
          subcategory: [
            {
              key: "country",
              name: "Country",
            },
          ],
          name: "Argentina",
          abbrv: null,
          location_id: "294266",
        },
      ],
      detail: "0",
      page_type: "hotels",
      mob_ptype: "app_hotels",
    },
    {
      location_id: "2548992",
      name: "Departamentos Misiones",
      latitude: "-27.363749",
      longitude: "-55.89968",
      num_reviews: "41",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/02/60/99/40/departamentos-misiones.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/02/60/99/40/departamentos-misiones.jpg",
            height: "50",
          },
          original: {
            width: "1504",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/02/60/99/40/departamentos-misiones.jpg",
            height: "1000",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/02/60/99/40/departamentos-misiones.jpg",
            height: "365",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/02/60/99/40/departamentos-misiones.jpg",
            height: "165",
          },
        },
        is_blessed: false,
        uploaded_date: "2012-03-13T11:56:06-0400",
        caption: "Loft",
        id: "39885120",
        helpful_votes: "5",
        published_date: "2012-03-13T11:59:55-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.3594844341278076",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "23",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#23 Best Value of 72 places to stay in Posadas",
      subcategory_type: "condo",
      subcategory_type_label: "Condominium",
      distance: "0.48462335324995864",
      distance_string: null,
      bearing: "northwest",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "07e220fe-20f4-47b9-9443-80915bfb4688",
    },
    {
      location_id: "7047468",
      name: "Rihotel",
      latitude: "-27.392729",
      longitude: "-55.899467",
      num_reviews: "37",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/06/b2/0c/7e/rihotel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/06/b2/0c/7e/rihotel.jpg",
            height: "50",
          },
          original: {
            width: "960",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/06/b2/0c/7e/rihotel.jpg",
            height: "638",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/06/b2/0c/7e/rihotel.jpg",
            height: "365",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/06/b2/0c/7e/rihotel.jpg",
            height: "166",
          },
        },
        is_blessed: true,
        uploaded_date: "2014-10-07T22:51:36-0400",
        caption: "nuestro variado y delicioso desayuno buffet",
        id: "112331902",
        helpful_votes: "1",
        published_date: "2014-10-09T03:57:52-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.3521311283111572",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "24",
      ranking_denominator: "72",
      ranking_category: "bb",
      ranking: "#24 Best Value of 72 places to stay in Posadas",
      subcategory_type: "small_hotel",
      subcategory_type_label: "Small Hotel",
      distance: "1.8553937441409316",
      distance_string: null,
      bearing: "south",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "3f9e689f-8a79-4b85-86ea-b41cc1b42f15",
    },
    {
      location_id: "2218492",
      name: "Posadena Linda Hostel",
      latitude: "-27.3675",
      longitude: "-55.889843",
      num_reviews: "119",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/05/7b/35/1e/posadena-linda-hostel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/05/7b/35/1e/posadena-linda-hostel.jpg",
            height: "50",
          },
          original: {
            width: "900",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/05/7b/35/1e/posadena-linda-hostel.jpg",
            height: "682",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/05/7b/35/1e/posadena-linda-hostel.jpg",
            height: "416",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/05/7b/35/1e/posadena-linda-hostel.jpg",
            height: "189",
          },
        },
        is_blessed: true,
        uploaded_date: "2014-03-06T07:16:48-0500",
        caption: "Hostel Posadeña Linda vistas espacios",
        id: "91960606",
        helpful_votes: "6",
        published_date: "2014-03-06T07:16:48-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2015",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2015_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2015",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2014",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2014_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2014",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.2807388305664062",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "25",
      ranking_denominator: "72",
      ranking_category: "hotel",
      ranking: "#25 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.17339758113523301",
      distance_string: null,
      bearing: "east",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "15385eee-fafa-463e-b260-92cb62022050",
    },
    {
      location_id: "609429",
      name: "Estancia Santa Ines",
      latitude: "-27.63319",
      longitude: "-55.81662",
      num_reviews: "27",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/01/1d/1e/74/the-main-house.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/01/1d/1e/74/the-main-house.jpg",
            height: "50",
          },
          original: {
            width: "2816",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/01/1d/1e/74/the-main-house.jpg",
            height: "2112",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/01/1d/1e/74/the-main-house.jpg",
            height: "413",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/01/1d/1e/74/the-main-house.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2008-11-04T19:19:25-0500",
        caption: "The main house",
        id: "18685556",
        helpful_votes: "19",
        published_date: "2008-11-07T20:42:07-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.2205114364624023",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "26",
      ranking_denominator: "72",
      ranking_category: "bb",
      ranking: "#26 Best Value of 72 places to stay in Posadas",
      subcategory_type: "bed_and_breakfast",
      subcategory_type_label: "Bed and Breakfast",
      distance: "19.016561727113697",
      distance_string: null,
      bearing: "south",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "a44aca06-9cec-4088-aa1f-2680b3261dd3",
    },
    {
      location_id: "611352",
      name: "Estancia Santa Cecilia",
      latitude: "-27.35958",
      longitude: "-55.92144",
      num_reviews: "29",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/01/6d/dd/bb/schlafzimmer.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/01/6d/dd/bb/schlafzimmer.jpg",
            height: "50",
          },
          original: {
            width: "3648",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/01/6d/dd/bb/schlafzimmer.jpg",
            height: "2736",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/01/6d/dd/bb/schlafzimmer.jpg",
            height: "413",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/01/6d/dd/bb/schlafzimmer.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2010-02-22T12:31:41-0500",
        caption: "Schlafzimmer",
        id: "23977403",
        helpful_votes: "3",
        published_date: "2010-02-26T08:56:50-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.2084968090057373",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "27",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#27 Best Value of 72 places to stay in Posadas",
      subcategory_type: "ranch",
      subcategory_type_label: "Ranch",
      distance: "1.844083857367727",
      distance_string: null,
      bearing: "west",
      rating: "5.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$$",
      price: "$200",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "1e04903b-afcc-4c51-bfb3-efe81ea0eb0b",
    },
    {
      location_id: "5498693",
      name: "Gualambao Hostel",
      latitude: "-27.383057",
      longitude: "-55.89449",
      num_reviews: "17",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/06/dc/0a/9a/gualambao-hostel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/06/dc/0a/9a/gualambao-hostel.jpg",
            height: "50",
          },
          original: {
            width: "2000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/06/dc/0a/9a/gualambao-hostel.jpg",
            height: "1324",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/06/dc/0a/9a/gualambao-hostel.jpg",
            height: "364",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/06/dc/0a/9a/gualambao-hostel.jpg",
            height: "166",
          },
        },
        is_blessed: true,
        uploaded_date: "2014-11-06T16:26:38-0500",
        caption: "Habitación Quíntuple",
        id: "115083930",
        helpful_votes: "0",
        published_date: "2014-11-06T16:26:38-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [
        {
          award_type: "GreenLeader",
          year: "2022",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/greenleader_small-0-5.png",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/greenleader_large_partner-0-5.jpg",
          },
          categories: ["GreenPartner"],
          display_name: "GreenLeader GreenPartner",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.1836695671081543",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "28",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#28 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hostel",
      subcategory_type_label: "Hostel",
      distance: "1.1428125450545412",
      distance_string: null,
      bearing: "south",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$1 - $2",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "24ff593a-b717-4fe2-85a6-0b08f0eea348",
    },
    {
      location_id: "15130450",
      name: "Irova Apart Hotel",
      latitude: "-27.399973",
      longitude: "-55.944412",
      num_reviews: "5",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/14/d2/ce/41/departamentos-dentro.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/14/d2/ce/41/departamentos-dentro.jpg",
            height: "50",
          },
          original: {
            width: "6000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/14/d2/ce/41/departamentos-dentro.jpg",
            height: "4000",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/14/d2/ce/41/departamentos-dentro.jpg",
            height: "367",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/14/d2/ce/41/departamentos-dentro.jpg",
            height: "167",
          },
        },
        is_blessed: true,
        uploaded_date: "2018-09-26T22:34:37-0400",
        caption: "Departamentos dentro del complejo Irova Apart Hotel",
        id: "349359681",
        helpful_votes: "0",
        published_date: "2018-09-26T22:34:37-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.1049387454986572",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "29",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#29 Best Value of 72 places to stay in Posadas",
      subcategory_type: "condo",
      subcategory_type_label: "Condominium",
      distance: "3.9355966145396666",
      distance_string: null,
      bearing: "southwest",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$62",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "05464e5d-991d-4599-bba7-05739910433f",
    },
    {
      location_id: "7690134",
      name: "Desiderata Hostel",
      latitude: "-27.372614",
      longitude: "-55.886856",
      num_reviews: "11",
      timezone: "America/Argentina/Cordoba",
      location_string: "Posadas, Province of Misiones, Litoral",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/07/54/59/76/habitacion-2.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/07/54/59/76/habitacion-2.jpg",
            height: "50",
          },
          original: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/07/54/59/76/habitacion-2.jpg",
            height: "363",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/07/54/59/76/habitacion-2.jpg",
            height: "363",
          },
          medium: {
            width: "480",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/07/54/59/76/habitacion-2.jpg",
            height: "317",
          },
        },
        is_blessed: true,
        uploaded_date: "2015-02-12T01:35:50-0500",
        caption: "Habitacion 2",
        id: "122968438",
        helpful_votes: "1",
        published_date: "2015-02-12T04:51:58-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Posadas Places to Stay",
      raw_ranking: "3.081596851348877",
      ranking_geo: "Posadas",
      ranking_geo_id: "312805",
      ranking_position: "30",
      ranking_denominator: "72",
      ranking_category: "other",
      ranking: "#30 Best Value of 72 places to stay in Posadas",
      subcategory_type: "hostel",
      subcategory_type_label: "Hostel",
      distance: "0.5395130693833148",
      distance_string: null,
      bearing: "southeast",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "d654fbc1-3963-41ee-b0ea-876ebf4d81ba",
    },
  ],
  status: {
    unfiltered_total_size: "72",
    commerce_country_iso_code: "US",
    autobroadened: true,
    progress: "100",
    auction_key: "c2c7d80c84c544b389fc7e9bd34378dc",
    primary_geo: "312805",
    pricing: "base",
    doubleClickZone: "sa.argentina.litoral",
  },
  paging: {
    results: "30",
    total_results: "72",
  },
};

//Mi test

let arrayDeObjetos = miObjeto.data;
let arrayIds = [];

arrayDeObjetos.map((hotel) => {
  arrayIds.push(hotel.location_id);
});

console.log(arrayIds);

//map de mi array de ids
arrayIds.map((idHotel) => {
  //wait axios dame tal cosa por idHotel
});

nuevocambio;
