var axios = require("axios");

let mockPosta = {
  hotel_id: 8051135,
  score_breakdown: [
    {
      from_year: 2022,
      count: 5,
      average_score: "9.3",
      customer_type: "solo_traveller",
      question: [
        {
          count: 5,
          localized_question: "Cleanliness",
          score: "10.0",
          question: "hotel_clean",
          score_comparison_to_ufi_average: 1,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_comfort",
          score: 9.5,
          localized_question: "Comfort",
          count: 5,
        },
        {
          score: 9.5,
          localized_question: "Facilities",
          count: 5,
          score_comparison_to_ufi_average: 1,
          question: "hotel_services",
        },
        {
          localized_question: "Location",
          score: 8.5,
          count: 5,
          score_comparison_to_ufi_average: 0,
          question: "hotel_location",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_staff",
          score: 9.5,
          localized_question: "Staff",
          count: 5,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "total",
          localized_question: "Total",
          score: 9.4,
          count: 5,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_value",
          score: "9.0",
          localized_question: "Value for money",
          count: 5,
        },
      ],
    },
    {
      from_year: 2022,
      count: 36,
      average_score: "9.0",
      customer_type: "couple",
      question: [
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_clean",
          score: 9.5,
          localized_question: "Cleanliness",
          count: 36,
        },
        {
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 0,
          count: 36,
          localized_question: "Comfort",
          score: 9.3,
        },
        {
          score: 9.5,
          localized_question: "Facilities",
          count: 36,
          score_comparison_to_ufi_average: 1,
          question: "hotel_services",
        },
        {
          score_comparison_to_ufi_average: -1,
          question: "hotel_location",
          localized_question: "Location",
          score: 7.1,
          count: 36,
        },
        {
          question: "hotel_staff",
          score_comparison_to_ufi_average: 0,
          count: 36,
          score: 9.4,
          localized_question: "Staff",
        },
        {
          score: 9.2,
          localized_question: "Total",
          count: 36,
          score_comparison_to_ufi_average: 0,
          question: "total",
        },
        {
          localized_question: "Value for money",
          score: 8.7,
          count: 36,
          score_comparison_to_ufi_average: 0,
          question: "hotel_value",
        },
        {
          question: "hotel_wifi",
          score_comparison_to_ufi_average: 0,
          count: 3,
          localized_question: "WiFi",
          score: 9.2,
        },
      ],
    },
    {
      from_year: 2022,
      count: 64,
      customer_type: "total",
      question: [
        {
          count: 64,
          score: 9.6,
          localized_question: "Cleanliness",
          question: "hotel_clean",
          score_comparison_to_ufi_average: 0,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_comfort",
          score: 9.4,
          localized_question: "Comfort",
          count: 64,
        },
        {
          score: 9.5,
          localized_question: "Facilities",
          count: 64,
          score_comparison_to_ufi_average: 1,
          question: "hotel_services",
        },
        {
          question: "hotel_location",
          score_comparison_to_ufi_average: 0,
          count: 64,
          score: 7.6,
          localized_question: "Location",
        },
        {
          localized_question: "Staff",
          score: 9.4,
          count: 64,
          score_comparison_to_ufi_average: 0,
          question: "hotel_staff",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "total",
          score: 9.2,
          localized_question: "Total",
          count: 64,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_value",
          localized_question: "Value for money",
          score: 8.9,
          count: 64,
        },
        {
          score_comparison_to_ufi_average: 1,
          question: "hotel_wifi",
          localized_question: "WiFi",
          score: 9.4,
          count: 4,
        },
      ],
      average_score: "9.1",
    },
    {
      average_score: "9.0",
      customer_type: "group",
      question: [
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_clean",
          localized_question: "Cleanliness",
          score: 9.4,
          count: 4,
        },
        {
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 0,
          count: 4,
          localized_question: "Comfort",
          score: 9.4,
        },
        {
          count: 4,
          score: 8.8,
          localized_question: "Facilities",
          question: "hotel_services",
          score_comparison_to_ufi_average: 0,
        },
        {
          score: 9.4,
          localized_question: "Location",
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "hotel_location",
        },
        {
          score: 8.1,
          localized_question: "Staff",
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "hotel_staff",
        },
        {
          localized_question: "Total",
          score: 8.3,
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "total",
        },
        {
          score: 9.4,
          localized_question: "Value for money",
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "hotel_value",
        },
      ],
      count: 4,
      from_year: 2022,
    },
    {
      average_score: "9.0",
      question: [
        {
          count: 36,
          score: 9.5,
          localized_question: "Cleanliness",
          question: "hotel_clean",
          score_comparison_to_ufi_average: 0,
        },
        {
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 0,
          count: 36,
          score: 9.3,
          localized_question: "Comfort",
        },
        {
          score: 9.5,
          localized_question: "Facilities",
          count: 36,
          score_comparison_to_ufi_average: 1,
          question: "hotel_services",
        },
        {
          score_comparison_to_ufi_average: -1,
          question: "hotel_location",
          localized_question: "Location",
          score: 7.1,
          count: 36,
        },
        {
          count: 36,
          score: 9.4,
          localized_question: "Staff",
          question: "hotel_staff",
          score_comparison_to_ufi_average: 0,
        },
        {
          question: "total",
          score_comparison_to_ufi_average: 0,
          count: 36,
          localized_question: "Total",
          score: 9.2,
        },
        {
          question: "hotel_value",
          score_comparison_to_ufi_average: 0,
          count: 36,
          score: 8.7,
          localized_question: "Value for money",
        },
        {
          localized_question: "WiFi",
          score: 9.2,
          count: 3,
          score_comparison_to_ufi_average: 0,
          question: "hotel_wifi",
        },
      ],
      customer_type: "young_couple",
      count: 36,
      from_year: 2022,
    },
    {
      count: 4,
      from_year: 2022,
      average_score: "8.6",
      question: [
        {
          score: 9.4,
          localized_question: "Cleanliness",
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "hotel_clean",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_comfort",
          localized_question: "Comfort",
          score: 9.4,
          count: 4,
        },
        {
          score_comparison_to_ufi_average: 1,
          question: "hotel_services",
          localized_question: "Facilities",
          score: 9.4,
          count: 4,
        },
        {
          localized_question: "Location",
          score: 8.1,
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "hotel_location",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_staff",
          localized_question: "Staff",
          score: 8.1,
          count: 4,
        },
        {
          localized_question: "Total",
          score: 8.5,
          count: 4,
          score_comparison_to_ufi_average: 0,
          question: "total",
        },
        {
          count: 4,
          localized_question: "Value for money",
          score: 8.8,
          question: "hotel_value",
          score_comparison_to_ufi_average: 0,
        },
        {
          count: 1,
          localized_question: "WiFi",
          score: 7.5,
          question: "hotel_wifi",
          score_comparison_to_ufi_average: 0,
        },
      ],
      customer_type: "review_category_business_travellers",
    },
    {
      count: 17,
      from_year: 2022,
      customer_type: "family_with_young_children",
      question: [
        {
          score: 9.9,
          localized_question: "Cleanliness",
          count: 17,
          score_comparison_to_ufi_average: 1,
          question: "hotel_clean",
        },
        {
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 1,
          count: 17,
          score: 9.6,
          localized_question: "Comfort",
        },
        {
          score_comparison_to_ufi_average: 1,
          question: "hotel_services",
          score: 9.7,
          localized_question: "Facilities",
          count: 17,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_location",
          localized_question: "Location",
          score: 8.1,
          count: 17,
        },
        {
          score: 9.9,
          localized_question: "Staff",
          count: 17,
          score_comparison_to_ufi_average: 1,
          question: "hotel_staff",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "total",
          score: 9.5,
          localized_question: "Total",
          count: 17,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_value",
          score: 9.1,
          localized_question: "Value for money",
          count: 17,
        },
        {
          question: "hotel_wifi",
          score_comparison_to_ufi_average: 1,
          count: 1,
          localized_question: "WiFi",
          score: "10.0",
        },
      ],
      average_score: "9.5",
    },
    {
      from_year: 2022,
      count: 6,
      average_score: "9.0",
      customer_type: "",
      question: [
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_clean",
          localized_question: "Cleanliness",
          score: 9.2,
          count: 6,
        },
        {
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 1,
          count: 6,
          score: 9.6,
          localized_question: "Comfort",
        },
        {
          count: 6,
          localized_question: "Facilities",
          score: 8.8,
          question: "hotel_services",
          score_comparison_to_ufi_average: 0,
        },
        {
          score: 8.8,
          localized_question: "Location",
          count: 6,
          score_comparison_to_ufi_average: 0,
          question: "hotel_location",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "hotel_staff",
          localized_question: "Staff",
          score: 8.3,
          count: 6,
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "total",
          score: 8.5,
          localized_question: "Total",
          count: 6,
        },
        {
          score_comparison_to_ufi_average: 1,
          question: "hotel_value",
          score: 9.6,
          localized_question: "Value for money",
          count: 6,
        },
      ],
    },
    {
      customer_type: "with_friends",
      question: [
        {
          question: "hotel_clean",
          score_comparison_to_ufi_average: 0,
          count: 2,
          score: 8.8,
          localized_question: "Cleanliness",
        },
        {
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 1,
          count: 2,
          localized_question: "Comfort",
          score: "10.0",
        },
        {
          localized_question: "Facilities",
          score: 8.8,
          count: 2,
          score_comparison_to_ufi_average: 0,
          question: "hotel_services",
        },
        {
          score: 7.5,
          localized_question: "Location",
          count: 2,
          score_comparison_to_ufi_average: 0,
          question: "hotel_location",
        },
        {
          count: 2,
          score: 8.8,
          localized_question: "Staff",
          question: "hotel_staff",
          score_comparison_to_ufi_average: 0,
        },
        {
          score: "9.0",
          localized_question: "Total",
          count: 2,
          score_comparison_to_ufi_average: 0,
          question: "total",
        },
        {
          question: "hotel_value",
          score_comparison_to_ufi_average: 1,
          count: 2,
          localized_question: "Value for money",
          score: "10.0",
        },
      ],
      average_score: "9.0",
      from_year: 2022,
      count: 2,
    },
    {
      average_score: "9.5",
      question: [
        {
          localized_question: "Cleanliness",
          score: 9.9,
          count: 17,
          score_comparison_to_ufi_average: 1,
          question: "hotel_clean",
        },
        {
          count: 17,
          localized_question: "Comfort",
          score: 9.6,
          question: "hotel_comfort",
          score_comparison_to_ufi_average: 1,
        },
        {
          question: "hotel_services",
          score_comparison_to_ufi_average: 1,
          count: 17,
          score: 9.7,
          localized_question: "Facilities",
        },
        {
          count: 17,
          score: 8.1,
          localized_question: "Location",
          question: "hotel_location",
          score_comparison_to_ufi_average: 0,
        },
        {
          score: 9.9,
          localized_question: "Staff",
          count: 17,
          score_comparison_to_ufi_average: 1,
          question: "hotel_staff",
        },
        {
          score_comparison_to_ufi_average: 0,
          question: "total",
          localized_question: "Total",
          score: 9.5,
          count: 17,
        },
        {
          localized_question: "Value for money",
          score: 9.1,
          count: 17,
          score_comparison_to_ufi_average: 0,
          question: "hotel_value",
        },
        {
          score_comparison_to_ufi_average: 1,
          question: "hotel_wifi",
          localized_question: "WiFi",
          score: "10.0",
          count: 1,
        },
      ],
      customer_type: "family",
      from_year: 2022,
      count: 17,
    },
  ],
};
//test

var mockData = {
  id: `${mockPosta.hotel_id}`,
  type: "Hotel",
  name: {
    type: "Text",
    value: "nombre x",
  },
  promedioHotel: {
    type: "Float",
    value: mockPosta.score_breakdown[2].average_score,
  },
  question: {
    type: "categorias",
    value: [
      {
        score: mockPosta.score_breakdown[0].question[0].score,
        question: "hotel_clean",
      },
      {
        score: mockPosta.score_breakdown[0].question[1].score,
        question: "hotel_comfort",
      },
    ],
  },
};


var data = JSON.stringify({
  actionType: "append",
  entities: [mockData],
});

var config = {
  method: "post",
  url: "http://localhost:1026/v2/op/update",
  headers: {
    "Content-Type": "application/json",
  },
  data: data,
};

axios(config)
  .then(function (response) {
    
  })
  .catch(function (error) {
    console.log(error);
  });
